services:
  app:
    image: graphout_image
    pull_policy: never
    container_name: graphout
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:5000:5000"
    volumes:
      - ./src:/app/src
      - ./docs:/app/docs